### ISSUE TITLE
Issues with downloading files feature

### ISSUE THREAD

**Issue by njosefbeck** [njosefbeck/gatsby-source-stripe#13]
@brxck 
Hey! The downloading files integration needs to be looked at a bit, if you have the time. Ran into some issues recently.

(1) For some reason, I can't get "localFiles" to show up anymore for Skus. I'm running the latest version of Gatsby, am getting no console errors, but when I go to query the "localFiles" field in GraphiQL it says the field is unqueryable. I haven't tested other Stripe object types, but thought I'd reach out about Skus to begin with.

```graphql
{
  allStripeSku {
    edges {
      node {
        id,
        active,
        localFiles,
        product {
          id
        }
      }
    }
  }
}
```

Here's the contents my gatsby-config.js file in case that's helpful.

```javascript
module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    {
    resolve: `gatsby-source-stripe`,
    options: {
      objects: ['Sku'],
      secretKey: 'xxx',
      downloadFiles: true
    }
  }
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.app/offline
    // 'gatsby-plugin-offline',
  ],
}

```

(2) If you run the plugin with the same exact config as found in the README, it errors out. In LocalFile.js, line 16 seems to error out because "fields" becomes undefined and line 47 errors out because payload.data is undefined. Maybe there needs to be some logic in there to return early if certain things don't exist.

```javascript
// In your gatsby-config.js
plugins: [
  {
    resolve: `gatsby-source-stripe`,
    options: {
      objects: ['Balance', 'BalanceTransaction', 'Product', 'ApplicationFee', 'Sku', 'Subscription'],
      secretKey: 'stripe_secret_key_here',
      downloadFiles: true
    }
  }
]
```

Let me know if you have the bandwidth to look into these things, otherwise I can dig deeper! Thanks!

**Comment by brxck** [comment]
Hmm. I will definitely give it a look! Keep you updated.

**Comment by brxck** [comment]
I'm still not entirely sure about your first issue here; I fixed some things, but I don't think they would be preventing sku images from downloading with the gatsby-config you provided. Who knows though, give it a shot with the new commits. :crossed_fingers: 

I've at least got sku image downloading working in a test repo right now. If it's still not working we'll probably have to dig a little deeper.

**Comment by njosefbeck** [comment]
Thanks for taking a look, and applying those fixes. Seemed to have solved (2), which is great! Still not seeing any localFiles for my sku though, unfortunately.

If you could email me (njosefbeck@gmail.com), maybe we can coordinate a way to debug together, or something. Alternatively, I could send along the Gatsby site code and see if you get localFiles for skus when you run the site locally.

**Comment by brxck** [comment]
Sure we can do that!
Two things that have bit me before, just in case:
1. Are the images definitely defined on the Stripe Sku node, and not the Product?
2. Are the images hosted in a way that they're accessible to createRemoteFileNode?

**Comment by njosefbeck** [comment]
So I confirmed that there are image files on the Stripe Sku, and when I go to the image file directly in the browser it downloads it. Would this mean that the images are hosted in a way that makes them accessible to createRemoteFileNode?

If you want to play around with my test Stripe token and see if you get different results, that'd be great! I can email it to you (provided I have your email address), or send it over Twitter - just let me know what works best for ya.

Here's my gatsby.config
```javascript
module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    {
    resolve: `gatsby-source-stripe`,
    options: {
      objects: ['Sku'],
      secretKey: 'xxx',
      downloadFiles: true
    }
  }
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.app/offline
    // 'gatsby-plugin-offline',
  ],
}
```

and here's my package.json

```javascript
{
  "name": "gatsby-starter-default",
  "private": true,
  "description": "A simple starter to get up and developing quickly with Gatsby",
  "version": "0.1.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "gatsby": "^2.0.89",
    "gatsby-image": "^2.0.20",
    "gatsby-plugin-manifest": "^2.0.13",
    "gatsby-plugin-offline": "^2.0.21",
    "gatsby-plugin-react-helmet": "^3.0.2",
    "gatsby-plugin-sharp": "^2.0.17",
    "gatsby-source-filesystem": "^2.0.13",
    "gatsby-transformer-sharp": "^2.1.10",
    "prop-types": "^15.6.2",
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "react-helmet": "^5.2.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "start": "npm run develop",
    "format": "prettier --write \"src/**/*.js\"",
    "test": "echo \"Write tests! -> https://gatsby.app/unit-testing\""
  },
  "devDependencies": {
    "prettier": "^1.15.2"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  }
}
```

This is also with the plugin copied into the `plugins` directory, and not npm installed.

**Comment by brxck** [comment]
Everything looks like it _should_ be working, so I'm gonna shoot you an email so I can get that token and start digging.

**Comment by brxck** [comment]
Alright, here's the update:
I can't get your Stripe data to work either. 

gatsby-source-filesystem's createRemoteFileNode is not getting along well with the Stripe-hosted image on your Sku. I haven't dug into the cRFN code yet, and it doesn't log or throw errors, so I'm not sure _why_ yet.

I imagine it's because Stripe's file links don't contain the filename or extension in the url, that information is passed through the response headers (?), ex. `https://files.stripe.com/links/fl_test_jVH0tv4lHCmSayHvZi1WItgI` yields `_icon1.png_`

**Comment by njosefbeck** [comment]
Ohhh interesting. So for your Stripe sku images, you have them stored somewhere outside of Stripe, and when you created the Sku programmatically, you added an image URL to the field? 

Since I created the Sku through the Stripe dashboard, there's no option to just input a URL. You have to choose the file from the file system. So maybe if you're not able to figure out how to get it working with Stripe-hosted images, we can just add this as a caveat for the feature. How's that sound?

Thanks again for digging into it!

**Comment by brxck** [comment]
That's correct! Truthfully I don't know of a way to have Stripe host your image when you are creating a sku, are you using the Checkout beta? Even in the dashboard I only have the option of providing my own url.

Hopefully it doesn't come to making that caveat! I'll look into the necessary changes to gastby-source-filesystem, seems like I should be able to get this working.

**Comment by njosefbeck** [comment]
Aha! Yes, I am using the Checkout beta! So maybe I'll just add a note to the README that adds that caveat. And maybe once the new Checkout experience is out, we can see if this is still an issue. Thanks for doing all this testing. I'm glad we figured out what the issue was! I'll go ahead and publish to NPM your other file changes and my README update, and will close this issue.
