### ISSUE TITLE
Unknown argument "product" on field "allStripeSku" of type "Query"

### ISSUE THREAD

**Issue by brettdewoody** [njosefbeck/gatsby-source-stripe#16]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Read through the README fully
  * Ensured you are running Node v.10 or above
  * Made sure you're using at least Gatsby v.2.0.15
  * Checked that your issue isn't already filed

### Description

Using `product` argument on `allStripeSku` results in error `Unknown argument "product" on field "allStripeSku" of type "Query".` If the argument is changed to another argument, like `limit` it works as expected. The [documentation shows `product` is a valid argument](https://stripe.com/docs/api/skus/list).

### Steps to Reproduce

1. Consider the following query:
```
query productDetail {
  product: stripeProduct(id: {eq: "prod_NNNNN"}) {
    id
    name,
  },
  skus: allStripeSku(product: {eq: "prod_NNNNN"}) {
    edges {
      node {
        id
      }
    }
  }
}
```
**Expected behavior:** [What you expect to happen]
The query should return a single product, and all SKUs belonging to that product. 

**Actual behavior:** [What actually happens]
Returns an error `Unknown argument "product" on field "allStripeSku" of type "Query".`

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

os: Mac 10.14.3
node: 10.15.1
npm: 6.4.1
gatsby: 2.4.1
gatsby-source-stripe: 2.1.7

**Comment by brettdewoody** [comment]
Is the recommended thing to do here to use a `filter`? Like:

```
query product {
  product: stripeProduct(id: {eq: "prod_NNNNN"}) {
    id
    name,
  },
  skus: allStripeSku(
    filter:{
      product: {
        id: {eq: "prod_NNNNN"}
      }
    }
  ) {
    totalCount,
    edges {
      node {
        id,
        product {
          id
        },
      }
    }
  }
}

```

**Comment by njosefbeck** [comment]
Hello @brettdewoody!

With my plugin options in `gatsby-node.js` set as `objects: ['Sku']`, I'm able to filter Skus by their product's id. The query I used was identical to the one you used in your most recent message. This works for me. You can also add additional fields under product to get more information back.

```graphql
{
  allStripeSku(
    filter:{
      product: {
        id: {eq: "prod_BefIdmZERgt4It"}
      }
    }
  ) {
    edges {
      node {
        id
        product {
          id
          description
        }
      }
    }
  }
}
```

Ultimately, your data will be an array of Skus belonging to a specific product. For me personally, I would then do any kind of restructuring of that data in my JavaScript code. For example, if you wanted a data structure like:

```javascript
{
  product: {
    id: "prod_NNNN",
    skus: [..., ..., ...]
```

I would do that data massaging in my JavaScript wherever it made sense. Happy to discuss further! Also, if I'm waaay off the mark as far as what you're looking for, let me know, and we can troubleshoot further.

**Comment by brettdewoody** [comment]
Yes, the `filter` was the way to go and solved the issue.
