### ISSUE TITLE
Error: Cannot query field "localFiles" on type "StripeProduct".

### ISSUE THREAD

**Issue by brettdewoody** [njosefbeck/gatsby-source-stripe#17]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Read through the README fully
  * Ensured you are running Node v.10 or above
  * Made sure you're using at least Gatsby v.2.0.15
  * Checked that your issue isn't already filed

### Question

I'm using the Stripe Checkout Beta, as well as `images[]` field on Products. For Product images, an array of image URLs is added to a product via the Stripe API. These images are hosted elsewhere, in my case they live in the `static` directory of my Gatsby site. 

Here's an example of a query and it's response:

**Query**
```
query allProducts {
    products: allStripeProduct {
      edges {
        node {
          id
          images
        }
      }
    }
  }
```

**Response**
```
{
  "data": {
    "products": {
      "edges": [
        {
          "node": {
            "id": "prod_EcDfq1CvGkdgbc",
            "images": [
              "http://localhost:8000/products/600.jpg"
            ]
          }
        },
        ...
      ]
    }
  }
}
```

If I change the query to add `localFiles`, an error is returned.

**Query**
```
query allProducts {
    products: allStripeProduct {
      edges {
        node {
          id
          images
          localFiles
        }
      }
    }
  }
```

**Response**
```
{
  "errors": [
    {
      "message": "Cannot query field \"localFiles\" on type \"StripeProduct\".",
      "locations": [
        {
          "line": 7,
          "column": 11
        }
      ]
    }
  ]
}
```

I've reviewed the existing issues related to this but it seems I'm doing everything correctly. I'm using Checkout Beta, but I believe that only comes into play on SKU images. 

Is the current version of `gatsby-source-stripe` setup to work with the Product images array?

### Versions

os: Mac 10.14.3
node: 10.15.1
npm: 6.4.1
gatsby: 2.1.17
gatsby-source-stripe: 2.1.7

**Comment by njosefbeck** [comment]
Hi @brettdewoody! Thanks for making this issue. As far as I know, Product images are supported by our download images feature. @brxck would be able to confirm, and be able to help you further debug.

In the interim, a couple of follow-up questions:
1. Do you have `downloadFiles: true` in the plugin's options in gatsby-config?
2. When you query local files, the query would be something like 
```
query allProducts {
    products: allStripeProduct {
      edges {
        node {
          id
          images
          localFiles {
            id
          }
        }
      }
    }
  }
```
Note the way I'm expanding the localFiles field. Does this also not work for you?

Answering these questions will help us debug. Also, as an aside, you opened another issue in this repo that I responded to awhile back. Is that issue resolved? If you could go over there and let us know, that'd be great. Thanks!

**Comment by brettdewoody** [comment]
Thanks for the speedy response. 

1. Yes, I have `downloadFiles: true` in `gatsby-config`, here is my config:

```
   {
      resolve: 'gatsby-source-stripe',
      options: {
        objects: ['Sku', 'Product'],
        secretKey: [SECRET_KEY],
        downloadFiles: true,
      },
    },
```
2. I also tried the query you suggested with the expanded `localFiles` but it returns the same error

**Comment by brettdewoody** [comment]
This could be related, I've noticed when I start `gatsby`, using `npm start` the following error occurs:

```
Error: Invariant Violation: Encountered an error trying to infer a GraphQL type for: "product.localFiles___NODE". There is no corresponding node with the id field mat  ching: "067fd1df-5418-556b-b255-964867adcf80,067fd1df-5418-556b-b255-964867adcf80,067fd1df-5418-556b-b255-964867adcf80,067fd1df-5418-556b-b255-964867adcf80"
```
To resolve this I `rm -rf .cache`, then `npm start` succeeds.

**Comment by brxck** [comment]
> I'm using Checkout Beta

I haven't been able to test with Checkout Beta yet, so this throws a red flag for me. I don't know under which circumstances downloading happens to work with Checkout Beta, so I wouldn't rely on it.

That last error is indicative of the file download failing, unfortunately the API we rely on doesn't surface those errors. I'm fairly certain this is a Checkout thing — not yet supported, but I will look into it!

**Comment by brxck** [comment]
Actually, I'm pretty sure this is the real issue:

> These images are hosted elsewhere, in my case they live in the static directory of my Gatsby site.

The Gatsby build lifecycle doesn't work in your favor here. Node creation happens before anything is hosted on the development server. So we are failing on download because a URL like `http://localhost:8000/products/600.jpg` doesn't resolve to an image yet. This be a problem in production as well.

I don't think there's yet a clear way to co-host the images, which need to be downloaded on build, your Gatsby site. I imagine we could support this in the future by adding another flag to search for images in the source? 

In the meantime you could probably add this sort of functionality to your own site by hooking into onCreateNode in gatsby-node.js. Otherwise it would probably be easiest to host the images separately from the site. A free host is sufficient because they will only ever be accessed by Gatsby on build.

**Comment by brettdewoody** [comment]
Ok, I see what you're saying. So if the images are moved to an external host it _should_ work. 

However, in GraphiQL, how will moving the images to an external source prevent the error of:

```
Cannot query field "localFiles" on type "StripeProduct".
```

**Comment by brxck** [comment]
Yep that's right!

That GraphQL error is an artifact of the same problem. No images were downloaded, Gatsby never had anything to put into the localFiles field, so it strips the field from the StripeProduct node type. It shouldn't be an issue if you get image downloading working.

**Comment by brettdewoody** [comment]
Ah, I see. Thanks for looking into this, much appreciated.
