### ISSUE TITLE
Avoid stripe secret key in gatsby-config?

### ISSUE THREAD

**Issue by JodyPSmith** [njosefbeck/gatsby-source-stripe#2]
Is there a way to avoid putting the stripe secret key in the gatsby-config and accessing it from an environment variable instead? I'm a little weary of including sensitive keys in the repo.

**Comment by njosefbeck** [comment]
Thanks for the question! I too would be leery of that. Thankfully you can use .env files to handle adding this kind of information to your gatsby-config.js file. More information can be found here: https://www.gatsbyjs.org/docs/environment-variables/

Let me know if you need any help with implementing a .env file! Closing for now.

**Comment by JodyPSmith** [comment]
Thanks for the link, I followed the guide and its working. Thanks for the link (and the source-stripe plugin too).
