### ISSUE TITLE
'Unable to find plugin' After 2.20 Update

### ISSUE THREAD

**Issue by brxck** [njosefbeck/gatsby-source-stripe#28]
I just updated to the newest release, but I'm running into this error on develop/build:

    error Unable to find plugin "gatsby-source-stripe". Perhaps you need to install its package?

I checked and the plugin is indeed in my node_modules. I've also tried deleting node_modules & package-lock.json and then reinstalling.

Same deal on both projects I tested.

@njosefbeck Looks like the publishing setup changed, maybe something's not quite right?

### Versions

os: Linux / Solus 4
node: 10.11.0
npm: 6.5.0
gatsby: 2.5.7
gatsby-source-stripe: 2.2.0

**Comment by njosefbeck** [comment]
Let me take a look!

**Comment by njosefbeck** [comment]
This is fixed! Apparently it's required to have an index.js file in the root of the plugin, even if it's empty. I've tested locally, but if you wouldn't mind updating to the new version (2.2.1) of the plugin and re-testing, it'd be much appreciated @brxck! Thanks!

**Comment by brxck** [comment]
Okay that cleared it up!

Running into another error:

    Error: Cannot find module './StripeObject'

Looks like a capitalization issue, the file's now named `stripeObject.js`. I looked back and I guess the old build process used to capitalize the file?

**Comment by njosefbeck** [comment]
Hmm, so I didn't run into that error myself. The file used to be capitalized but it isn't anymore. Have you tried deleting your node_modules and package-lock.json and doing a fresh npm install? Once you do that, if you look at gatsby-source-stripe in node_modules, is your file structure the same as below?

<img width="221" alt="Screen Shot 2019-04-13 at 1 05 35 PM" src="https://user-images.githubusercontent.com/9508002/56083607-e0ff3f00-5dec-11e9-816a-06533724f2e0.png">

**Comment by njosefbeck** [comment]
Oh just saw your edit! Was it that way in the latest version you get from NPM? Or in a local version you have in a plugins dir?

**Comment by brxck** [comment]
Yeah it was that way in the latest, even with a fresh install :thinking:

**Comment by njosefbeck** [comment]
Oh yeah, that's a bug then! I'll pull down your change and publish that to NPM then! Thanks!

**Comment by njosefbeck** [comment]
OK pushed up and published 2.2.2. Let me know if you encounter any further errors!

**Comment by brxck** [comment]
New version is working great, thanks!
