### ISSUE TITLE
Remove auth header entirely

### ISSUE THREAD

**Issue by Francesco-Lanciana** [njosefbeck/gatsby-source-stripe#29]
### Description

Turns out that files/images hosted on Stripe don't actually require you to authenticate with your Stripe credentials. They are entirely public. This means that there isn't ever a need for you to provide the auth header - it should simply always be removed. I have tested this locally and can now successfully pull down all images. 

I'm happy to create a PR that will remove the auth option, remove the auth header in every instance, and simplify LocalFile.js since the downloadStripeHostedFile method is now no longer needed. @njosefbeck @brxck let me know if I'm forgetting something important.

### Steps to Reproduce

1. Grab one of the URLs that points to an image hosted on Stripe.
2. Open up an incognito window and paste in the address. 
3. Hit enter and the file should download

This means that the file can be downloaded without any cookies being provided for authentication.

**Comment by Francesco-Lanciana** [comment]
I've sent an email to Stripe support to confirm whether or not all images hosted on Stripe are made public. I'll let you know as soon as I get a response.

**Comment by brxck** [comment]
Hey I think there's some misunderstanding here. I did not add in authentication for downloading images on Product or Sku nodes, but for downloading the contents of Stripe's File nodes, [which requires authentication](https://stripe.com/docs/api/files) (see the `url` field).

I'm not sure where authentication exists in LocalFile after your refactor, but it is not needed for Products and Skus, only Files.

**Comment by njosefbeck** [comment]
This has been removed as of v3.0.0.
