### ISSUE TITLE
Pagination never ends

### ISSUE THREAD

**Issue by raae** [njosefbeck/gatsby-source-stripe#3]
The pagination never ends as the args never change.

**Comment by njosefbeck** [comment]
@raae Thank you for this fix! Will merge this into the project.

**Comment by njosefbeck** [comment]
@raae If you have a moment to test the fix on a project, I've published the latest version with your change included up to npm. Would be much appreciated! Thanks!

**Comment by raae** [comment]
Tested it on the same project that was not working with the last version, and it is now working.
