### ISSUE TITLE
Support Node 8

### ISSUE THREAD

**Issue by KyleAMathews** [njosefbeck/gatsby-source-stripe#38]
Could you change your package.json `engines` to support the same versions as Gatsby e.g. 6+? Or at least 8+

Many people don't have Node 10 installed still so this plugin will break for them.

**Comment by KyleAMathews** [comment]
Many hosting providers also still default to node 8.

**Comment by njosefbeck** [comment]
Yeah, should be as simple as updating the `engines` and verifying that Babel properly transforms our use of `for-await-of`. Will get to it as soon as we can!

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by njosefbeck** [comment]
This should now be taken care of with our 3.0.0 release. Thanks for the heads up Kyle 👍 .
