### ISSUE TITLE
Possible to include `metadata` parameter in object response?

### ISSUE THREAD

**Issue by jasonbarry** [njosefbeck/gatsby-source-stripe#39]
The [metadata parameter](https://stripe.com/docs/api/metadata) is useful for showing arbitrary information related to certain Stripe objects. According to the docs, Account, Charge, Customer, PaymentIntent, Refund, Subscription, and Transfer support this property, and I know that Plan and Product do as well. 

Is it possible for `metadata` to be one of the queryable fields?

**Comment by njosefbeck** [comment]
@jasonbarry Thanks so much for reaching out! Have you stored `metadata` on one of the above Stripe objects, and have attempted to access that property and not been able to? If not, I can go ahead and add some `metadata` to something and see if it's already accessible. We don't do anything to limit the information returned by Stripe, so I'm assuming the key will be on there, but I haven't tested it.

Let me know! Thanks!

**Comment by jasonbarry** [comment]
@njosefbeck turns out I didn't restart GraphiQL after adding those metadata properties. Nothing to see here :-) thanks for maintaining a great plugin!

**Comment by njosefbeck** [comment]
@jasonbarry Sounds good! Your support is much appreciated. Please reach out if you ever run into any issues. ALSO, if you're using our plugin in a project, let us know and we can include it in the README.
