### ISSUE TITLE
Using gatsby-transformer-json in the same project causes build errors

### ISSUE THREAD

**Issue by nsamala** [njosefbeck/gatsby-source-stripe#40]
### Pre-requisites

  * [x] Read through the README fully
  * [x] Ensured you are running Node v.10 or above
  * [x] Made sure you're using at least Gatsby v.2.0.15
  * [x] Checked that your issue isn't already filed

### Description

When running `gatsby build` on a project that uses both `gatsby-source-stripe` and `gatsby-transformer-json`, the build fails with an error like the following:

```
Error: Nodes can only be updated by their owner. Node "prod_FKQdtEsTJLpdoG" is owned by "gatsby-source-stripe" and another plugin "gatsby-transformer-json" tried to update it.
```

With a non-zero exit code, the build fails.

### Steps to Reproduce

1. Create a new Gatsby project that uses `gatsby-source-stripe`
2. Add your stripe credentials via environment variable or `.env` file
3. Add `gatsby-transformer-json` to plugins section of `gatsby-config.js`
4. Run `gatsby build`

**Expected behavior:** `gatsby-transformer-node` does nothing to the Stripe object nodes

**Actual behavior:** `gatsby-transformer-node` sees an `application/json` node internal type and tries to transform it.

**Reproduces how often:** 100% of builds

### Versions

os: [version]
node: 10.13.0
npm: 6.7.0
gatsby: 2.10.4
gatsby-source-stripe: 3.0.1

### Additional Information

If you modify the plugin to use a different internal mediaType in `StripeObject.js`, the error disappears.

**Comment by nsamala** [comment]
nvm this doesn't work

**Comment by njosefbeck** [comment]
Apologies for the delayed response! This `mediaType` gets added [at this line](https://github.com/njosefbeck/gatsby-source-stripe/blob/cff0cacdb7abb8c662bc0ed6ff6d4dee50bcb789/src/StripeObject.js#L39) for anyone that might want to fix this before I can get to it. Otherwise I'll work on having this fixed by the end of this week.

Thanks for bringing this to our attention :+1:!

**Comment by njosefbeck** [comment]
@nsamala Sorry for the delay with this! New version 3.0.2 should be up on npm, if you wouldn't mind testing.

Once you've confirmed it works on your end, I'll close this issue. Thanks!

**Comment by njosefbeck** [comment]
No response from OP, going to close this for now. Please re-open if this is still an issue! Thanks.
