### ISSUE TITLE
Is there a way of getting back the price of a subscription (product)

### ISSUE THREAD

**Issue by jodiedoubleday** [njosefbeck/gatsby-source-stripe#51]
**Prerequisites**

[ X ] Put an X between the brackets on this line if you have done all of the following:
  * Read through the README fully.
  * Ensured you are running Node v.10 or above.
  * Made sure you're using at least Gatsby v.2.0.15.
  * Checked that your issue isn't already filed.

**Describe the bug**
Is there a way of getting back the price of a subscription (Product)

**Comment by njosefbeck** [comment]
Looks like you were able to make this happen? Feel free to reach out if you have other questions / run into any issues!
