### ISSUE TITLE
Price instead of SKU

### ISSUE THREAD

**Issue by vSterlin** [njosefbeck/gatsby-source-stripe#56]
It looks like SKUs are not used with Stripe Checkout anymore, they use Price object instead (there is no way to add SKU in Stripe dashboard). When I query allStripePrice with the plugin, I can retrieve the product's id but not its name, so I need a separate query for Stripe products to retrieve the product's name which is inconvenient. If it would be possible to retrieve product's name from price query it would be a great addition to plugin.

**Comment by njosefbeck** [comment]
Hello!

This will be easy enough to do, as it looks like [`product` is expandable on the Price object](https://stripe.com/docs/api/prices/object). I won't be able to get to this until later in the week, but if you want to follow the [pattern found in `stripeObjects.json`](https://github.com/njosefbeck/gatsby-source-stripe/blob/f22556bdbca290b93ed85dc1642afc9de794944d/src/stripeObjects.json#L419) for `expand`ing fields for other objects, feel free to add for `Price` and make a PR!

Thanks!

**Comment by brittneypostma** [comment]
It looks like the Price object has now been added to the stripeObjects.json is there a way to query for that now? The only example is see is still the allStripeSku, which does not work with newer accounts.

**Comment by njosefbeck** [comment]
@brittneypostma Hello! Having more examples of querying for other types of Stripe objects would be great - happy to accept any PRs updating the README with more examples.

As far as querying for Prices, have you tried adding it to your plugin config like so:

```
{
    resolve: `gatsby-source-stripe`,
    options: {
      objects: ['Price'],
      secretKey: 'stripe_secret_key_here',
    }
  }
``` 

If the above works, you should be able to open Graphiql and see `allStripePrice`. If you don't, happy to help you debug further!

@vSterlin also thanks for the PR, will get that merged this weekend!

**Comment by brittneypostma** [comment]
I have added it to the objects as shown above, but allStripe does not show up in Graphiql.

**Comment by njosefbeck** [comment]
Oh great! Glad to hear that querying is working! Looking forward to that PR and don't hesitate to reach out if you run into additional issues / have additional questions.

**Comment by njosefbeck** [comment]
This is now merged! Feel free to create a new issue if you run into an issue :)
