### ISSUE TITLE
Get Price in stripeProduct query

### ISSUE THREAD

**Issue by vSterlin** [njosefbeck/gatsby-source-stripe#60]
It would be very useful to be able to extract prices while querying allStripeProducts or stripeProduct. It is currently possible to get products from price query, but not other way around.

**Comment by njosefbeck** [comment]
Yeah, this seems to be a limitation of the Stripe API. At least, I don't see a `price` or `prices` key on the Product object: https://stripe.com/docs/api/products/object.

But, you should get back the fully expanded `Product` object when querying for all prices, so you could do some data massaging to add relevant prices to each product. I don't have a good example of doing this, but in theory it'd be possible to either do this in the frontend code or in `gatsby-node.js` via like.. expanding or linking nodes.
