### ISSUE TITLE
[HELP WANTED] - GatsbyV4 [bug] - error while running the sourceNodes lifecycle

### ISSUE THREAD

**Issue by jodiedoubleday** [njosefbeck/gatsby-source-stripe#69]
**Prerequisites**

[ X ] Put an X between the brackets on this line if you have done all of the following:
  * Read through the README fully.
  * Ensured you are running Node v.10 or above.
  * Made sure you're using at least Gatsby v.2.0.15.
  * Checked that your issue isn't already filed.

**Describe the bug**
I've updated to GtsabyV4 - When running my site i get the following error 
```
"gatsby-source-stripe" threw an error while running the sourceNodes lifecycle:
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
```

This is not necessarily a BUG but maybe a request to update to support Gatsby V4.

**To Reproduce**
1. Update all packages to the latest Gatsby V4
2. Run Gatsby in Develop or on Serve.
3. error appears, and does not allow Stripe Graphwl to be generated

**Expected behavior**
Everything to run smoothly and all Stripe Graphql data to appear.

**Screenshots**

<img width="602" alt="Screenshot 2021-11-01 at 16 50 22" src="https://user-images.githubusercontent.com/778942/139709072-077a4c15-0c40-4ac9-959b-950a38b83c84.png">

**Versions (please complete the following information):**

os: macOS Big Sur 11.6
node: v14.17.3
npm: 6.14.13
gatsby: 4.0.2
gatsby-source-stripe: 3.2.2

**Gatsby config:**

Copy the portion of your Gatsby config for this plugin here. **Do not include your `secretKey`.**

```js
{
      resolve: `gatsby-source-stripe`,
      options: {
        objects: ['Price'],
        secretKey: ...,
        downloadFiles: true
      }
    },
```

**Comment by njosefbeck** [comment]
Hello! Yes this is likely due to Gatsby v4 updates. I haven't used Gatsby in a long time, so if you or anyone else would like to contribute to updating this project to work with v4, it would be much appreciated. Otherwise it may take me a little bit to get around to this unfortunately.

**Comment by jodiedoubleday** [comment]
i;m not the best with gatsby plugins myself but I'll give it a damn good try 😄
